base_target_ema: 0.99
batch_size: 2
checkpoint:
  filename: smoke.pt
  save_dir: /tmp/byol3d_smoke
  save_every_epochs: 1
data:
  crop_size: 8
  data_dir: null
  in_channels: 1
  min_overlap: 0.4
  num_workers: 0
  pin_memory: false
  volume_size: 16
encoder:
  base_channels: 8
  channels: null
  in_channels: 1
  num_levels: 3
  use_residuals: true
logging:
  eval_every_epochs: 1
  log_every_steps: 1
lr_schedule:
  schedule: cosine
  warmup_epochs: 0
  warmup_steps: 0
max_steps: 4
num_epochs: 2
optimizer:
  betas: !!python/tuple
  - 0.9
  - 0.999
  lr: 0.001
  name: adamw
  weight_decay: 0.0001
predictor:
  hidden_dim: 32
projector:
  hidden_dim: 32
  output_dim: 16
random_seed: 42
steps_per_epoch: 2
