base_target_ema: 0.99
batch_size: 2
checkpoint:
  filename: byol3d_pretrain.pt
  save_dir: /tmp/test_lightning
  save_every_epochs: 50
data:
  cache_dir: null
  crop_size: 96
  data_dir: /nfs/khan/trainees/apooladi/abeta/nnssl_data/8/nnssl_data/preprocessed
  in_channels: 1
  min_overlap: 0.4
  num_workers: 8
  pin_memory: true
  volume_size: 256
encoder:
  base_channels: 32
  channels: null
  in_channels: 1
  num_levels: 5
  use_residuals: true
logging:
  eval_every_epochs: 25
  log_every_steps: 10
lr_schedule:
  schedule: cosine
  warmup_epochs: 10
  warmup_steps: 250
max_steps: 2500
num_epochs: 1
num_samples: 10000
optimizer:
  betas: !!python/tuple
  - 0.9
  - 0.999
  lr: 0.001
  name: adamw
  weight_decay: 0.0001
predictor:
  hidden_dim: 2048
projector:
  hidden_dim: 2048
  output_dim: 256
random_seed: 42
steps_per_epoch: 2500
